BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Card Traits" (
	"CARD_ID"	INTEGER,
	"TRAIT_NAME"	TEXT,
	PRIMARY KEY("CARD_ID","TRAIT_NAME"),
	FOREIGN KEY("CARD_ID") REFERENCES "Investigator Cards"("CARD_ID"),
	FOREIGN KEY("TRAIT_NAME") REFERENCES "Traits"("TRAIT_NAME")
);
CREATE TABLE IF NOT EXISTS "Investigator Cards" (
	"CARD_ID"	INTEGER NOT NULL UNIQUE,
	"CARD_NAME"	TEXT NOT NULL,
	"CARD_CLASS"	TEXT NOT NULL,
	"CARD_LEVEL"	INTEGER NOT NULL,
	"CARD_TYPE"	TEXT NOT NULL,
	"CARD_COST"	INTEGER,
	"SKILL_WILLPOWER"	INTEGER DEFAULT 0,
	"SKILL_INTELLECT"	INTEGER DEFAULT 0,
	"SKILL_COMBAT"	INTEGER DEFAULT 0,
	"SKILL_AGILITY"	INTEGER DEFAULT 0,
	"SKILL_WILD"	INTEGER DEFAULT 0,
	UNIQUE("CARD_NAME","CARD_CLASS","CARD_LEVEL"),
	PRIMARY KEY("CARD_NAME","CARD_LEVEL","CARD_CLASS"),
	FOREIGN KEY("CARD_TYPE") REFERENCES "Types"("TYPE_NAME")
);
CREATE TABLE IF NOT EXISTS "Traits" (
	"TRAIT_NAME"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("TRAIT_NAME")
);
CREATE TABLE IF NOT EXISTS "Types" (
	"TYPE_NAME"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("TYPE_NAME")
);
INSERT INTO "Investigator Cards" VALUES (1,'.45 Automatic','G',0,'Asset',4,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (2,'Physical Training','G',0,'Asset',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (3,'Beat Cop','G',0,'Asset',4,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (4,'First Aid','G',0,'Asset',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (5,'Machete','G',0,'Asset',3,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (6,'Guard Dog','G',0,'Asset',3,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (7,'Evidence!','G',0,'Event',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (8,'Dodge','G',0,'Event',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (9,'Dynamite Blast','G',0,'Event',5,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (10,'Vicious Blow','G',0,'Skill',NULL,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (11,'Extra Ammunition','G',1,'Event',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (12,'Police Badge','G',2,'Asset',3,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (13,'Beat Cop','G',2,'Asset',4,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (14,'Shotgun','G',4,'Asset',5,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (15,'Magnifying Glass','K',0,'Asset',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (16,'Old Book of Lore','K',0,'Asset',3,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (17,'Research Librarian','K',0,'Asset',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (18,'Dr. Milan Christopher','K',0,'Asset',4,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (19,'Hyperawareness','K',0,'Asset',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (20,'Medical Texts','K',0,'Asset',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (21,'Mind over Matter','K',0,'Event',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (22,'Working a Hunch','K',0,'Event',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (23,'Barricade','K',0,'Event',0,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (24,'Deduction','K',0,'Skill',NULL,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (25,'Magnifying Glass','K',1,'Asset',0,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (26,'Disc of Itzamna','K',2,'Asset',3,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (27,'Encyclopedia','K',2,'Asset',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (28,'Cryptic Research','K',4,'Event',0,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (29,'Switchblade','R',0,'Asset',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (30,'Burglary','R',0,'Asset',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (31,'Pickpocketing','R',0,'Asset',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (32,'.41 Derringer','R',0,'Asset',3,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (33,'Leo De Luca','R',0,'Asset',6,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (34,'Hard Knocks','R',0,'Asset',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (35,'Elusive','R',0,'Event',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (36,'Backstab','R',0,'Event',3,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (37,'Sneak Attack','R',0,'Event',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (38,'Opportunist','R',0,'Skill',NULL,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (39,'Leo De Luca','R',1,'Asset',5,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (40,'Cat Burglar','R',1,'Asset',4,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (41,'Sure Gamble','R',3,'Event',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (42,'Hot Streak','R',4,'Event',3,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (43,'Forbidden Knowledge','M',0,'Asset',0,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (44,'Holy Rosary','M',0,'Asset',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (45,'Shrivelling','M',0,'Asset',3,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (46,'Scrying','M',0,'Asset',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (47,'Arcane Studies','M',0,'Asset',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (48,'Arcane Initiate','M',0,'Asset',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (49,'Drawn to the Flame','M',0,'Event',0,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (50,'Ward of Protection','M',0,'Event',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (51,'Blinding Light','M',0,'Event',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (52,'Fearless','M',0,'Skill',NULL,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (53,'Mind Wipe','M',1,'Event',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (54,'Blinding Light','M',2,'Event',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (55,'Book of Shadows','M',3,'Asset',4,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (56,'Grotesque Statue','M',4,'Asset',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (57,'Leather Coat','S',0,'Asset',0,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (58,'Scavenging','S',0,'Asset',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (59,'Baseball Bat','S',0,'Asset',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (60,'Rabbit''s Foot','S',0,'Asset',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (61,'Stray Cat','S',0,'Asset',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (62,'Dig Deep','S',0,'Asset',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (63,'Cunning Distraction','S',0,'Event',5,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (64,'Look what I found!','S',0,'Event',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (65,'Lucky!','S',0,'Event',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (66,'Survival Instinct','S',0,'Skill',NULL,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (67,'Aquinnah','S',1,'Asset',5,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (68,'Close Call','S',2,'Event',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (69,'Lucky!','S',2,'Event',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (70,'Will to Survive','S',3,'Event',4,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (71,'Knife','N',0,'Asset',1,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (72,'Flashlight','N',0,'Asset',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (73,'Emergency Cache','N',0,'Event',0,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (74,'Guts','N',0,'Skill',NULL,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (75,'Perception','N',0,'Skill',NULL,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (76,'Overpower','N',0,'Skill',NULL,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (77,'Manual Dexterity','N',0,'Skill',NULL,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (78,'Unexpected Courage','N',0,'Skill',NULL,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (79,'Bulletproof Vest','N',3,'Asset',2,0,0,0,0,0);
INSERT INTO "Investigator Cards" VALUES (80,'Elder Sign Amulet','N',3,'Asset',2,0,0,0,0,0);
INSERT INTO "Traits" VALUES ('???');
INSERT INTO "Traits" VALUES ('Abandoned');
INSERT INTO "Traits" VALUES ('Abomination');
INSERT INTO "Traits" VALUES ('Abyss');
INSERT INTO "Traits" VALUES ('Act 1');
INSERT INTO "Traits" VALUES ('Act 2');
INSERT INTO "Traits" VALUES ('Agency');
INSERT INTO "Traits" VALUES ('Alexandria');
INSERT INTO "Traits" VALUES ('Ally');
INSERT INTO "Traits" VALUES ('Altered');
INSERT INTO "Traits" VALUES ('Ancient');
INSERT INTO "Traits" VALUES ('Ancient One');
INSERT INTO "Traits" VALUES ('Arkham');
INSERT INTO "Traits" VALUES ('Arkham Asylum');
INSERT INTO "Traits" VALUES ('Armor');
INSERT INTO "Traits" VALUES ('Artist');
INSERT INTO "Traits" VALUES ('Assistant');
INSERT INTO "Traits" VALUES ('Attack');
INSERT INTO "Traits" VALUES ('Augury');
INSERT INTO "Traits" VALUES ('Avatar');
INSERT INTO "Traits" VALUES ('Basement');
INSERT INTO "Traits" VALUES ('Bayou');
INSERT INTO "Traits" VALUES ('Bazaar');
INSERT INTO "Traits" VALUES ('Believer');
INSERT INTO "Traits" VALUES ('Blessed');
INSERT INTO "Traits" VALUES ('Blight');
INSERT INTO "Traits" VALUES ('Blunder');
INSERT INTO "Traits" VALUES ('Boat');
INSERT INTO "Traits" VALUES ('Bold');
INSERT INTO "Traits" VALUES ('Boon');
INSERT INTO "Traits" VALUES ('Bridge');
INSERT INTO "Traits" VALUES ('Broken');
INSERT INTO "Traits" VALUES ('Brotherhood');
INSERT INTO "Traits" VALUES ('Buenos Aires');
INSERT INTO "Traits" VALUES ('Byakhee');
INSERT INTO "Traits" VALUES ('Bystander');
INSERT INTO "Traits" VALUES ('Cairo');
INSERT INTO "Traits" VALUES ('Campsite');
INSERT INTO "Traits" VALUES ('Carnevale');
INSERT INTO "Traits" VALUES ('Casino');
INSERT INTO "Traits" VALUES ('Cave');
INSERT INTO "Traits" VALUES ('Central');
INSERT INTO "Traits" VALUES ('Charm');
INSERT INTO "Traits" VALUES ('Chosen');
INSERT INTO "Traits" VALUES ('Circle');
INSERT INTO "Traits" VALUES ('City');
INSERT INTO "Traits" VALUES ('Civic');
INSERT INTO "Traits" VALUES ('Clairvoyant');
INSERT INTO "Traits" VALUES ('Clothing');
INSERT INTO "Traits" VALUES ('Clover Club');
INSERT INTO "Traits" VALUES ('Coastal');
INSERT INTO "Traits" VALUES ('Colour');
INSERT INTO "Traits" VALUES ('Composure');
INSERT INTO "Traits" VALUES ('Condition');
INSERT INTO "Traits" VALUES ('Connection');
INSERT INTO "Traits" VALUES ('Conspirator');
INSERT INTO "Traits" VALUES ('Construct');
INSERT INTO "Traits" VALUES ('Corruption');
INSERT INTO "Traits" VALUES ('Coterie');
INSERT INTO "Traits" VALUES ('Covenant');
INSERT INTO "Traits" VALUES ('Creature');
INSERT INTO "Traits" VALUES ('Crime Scene');
INSERT INTO "Traits" VALUES ('Criminal');
INSERT INTO "Traits" VALUES ('Cultist');
INSERT INTO "Traits" VALUES ('Curse');
INSERT INTO "Traits" VALUES ('Cursed');
INSERT INTO "Traits" VALUES ('Dark Young');
INSERT INTO "Traits" VALUES ('Deep One');
INSERT INTO "Traits" VALUES ('Depths');
INSERT INTO "Traits" VALUES ('Desert');
INSERT INTO "Traits" VALUES ('Desperate');
INSERT INTO "Traits" VALUES ('Detective');
INSERT INTO "Traits" VALUES ('Developed');
INSERT INTO "Traits" VALUES ('Dhole');
INSERT INTO "Traits" VALUES ('Dilemma');
INSERT INTO "Traits" VALUES ('Distortion');
INSERT INTO "Traits" VALUES ('Double');
INSERT INTO "Traits" VALUES ('Dreamer');
INSERT INTO "Traits" VALUES ('Dreamlands');
INSERT INTO "Traits" VALUES ('Drifter');
INSERT INTO "Traits" VALUES ('Dunwich');
INSERT INTO "Traits" VALUES ('Eidolon');
INSERT INTO "Traits" VALUES ('Elder Thing');
INSERT INTO "Traits" VALUES ('Eldritch');
INSERT INTO "Traits" VALUES ('Elite');
INSERT INTO "Traits" VALUES ('Emissary');
INSERT INTO "Traits" VALUES ('Endtimes');
INSERT INTO "Traits" VALUES ('Entrepreneur');
INSERT INTO "Traits" VALUES ('Evidence');
INSERT INTO "Traits" VALUES ('Exhibit');
INSERT INTO "Traits" VALUES ('Expedition');
INSERT INTO "Traits" VALUES ('Expert');
INSERT INTO "Traits" VALUES ('Extradimensional');
INSERT INTO "Traits" VALUES ('Extraterrestrial');
INSERT INTO "Traits" VALUES ('Eztli');
INSERT INTO "Traits" VALUES ('Falcon Point');
INSERT INTO "Traits" VALUES ('Familiar');
INSERT INTO "Traits" VALUES ('Fated');
INSERT INTO "Traits" VALUES ('Favor');
INSERT INTO "Traits" VALUES ('Firearm');
INSERT INTO "Traits" VALUES ('Flaw');
INSERT INTO "Traits" VALUES ('Flora');
INSERT INTO "Traits" VALUES ('Footwear');
INSERT INTO "Traits" VALUES ('Forbidden');
INSERT INTO "Traits" VALUES ('Forgotten');
INSERT INTO "Traits" VALUES ('Fortune');
INSERT INTO "Traits" VALUES ('Future');
INSERT INTO "Traits" VALUES ('Gambit');
INSERT INTO "Traits" VALUES ('Geist');
INSERT INTO "Traits" VALUES ('Ghast');
INSERT INTO "Traits" VALUES ('Ghoul');
INSERT INTO "Traits" VALUES ('Glacier');
INSERT INTO "Traits" VALUES ('Government');
INSERT INTO "Traits" VALUES ('Grant');
INSERT INTO "Traits" VALUES ('Graveyard');
INSERT INTO "Traits" VALUES ('Ground Floor');
INSERT INTO "Traits" VALUES ('Guest');
INSERT INTO "Traits" VALUES ('Gug');
INSERT INTO "Traits" VALUES ('Hall');
INSERT INTO "Traits" VALUES ('Hardship');
INSERT INTO "Traits" VALUES ('Haunted');
INSERT INTO "Traits" VALUES ('Havana');
INSERT INTO "Traits" VALUES ('Hazard');
INSERT INTO "Traits" VALUES ('Hex');
INSERT INTO "Traits" VALUES ('Hideout');
INSERT INTO "Traits" VALUES ('Historical Society');
INSERT INTO "Traits" VALUES ('Humanoid');
INSERT INTO "Traits" VALUES ('Hunter');
INSERT INTO "Traits" VALUES ('Hybrid');
INSERT INTO "Traits" VALUES ('Illicit');
INSERT INTO "Traits" VALUES ('Improvised');
INSERT INTO "Traits" VALUES ('Injury');
INSERT INTO "Traits" VALUES ('Innate');
INSERT INTO "Traits" VALUES ('Innocent');
INSERT INTO "Traits" VALUES ('Innsmouth');
INSERT INTO "Traits" VALUES ('Insect');
INSERT INTO "Traits" VALUES ('Insight');
INSERT INTO "Traits" VALUES ('Instrument');
INSERT INTO "Traits" VALUES ('Island');
INSERT INTO "Traits" VALUES ('Istanbul');
INSERT INTO "Traits" VALUES ('Item');
INSERT INTO "Traits" VALUES ('Job');
INSERT INTO "Traits" VALUES ('Jungle');
INSERT INTO "Traits" VALUES ('Kadath');
INSERT INTO "Traits" VALUES ('Key');
INSERT INTO "Traits" VALUES ('Kuala Lumpur');
INSERT INTO "Traits" VALUES ('Lair');
INSERT INTO "Traits" VALUES ('Lead');
INSERT INTO "Traits" VALUES ('Leng');
INSERT INTO "Traits" VALUES ('Locus Site');
INSERT INTO "Traits" VALUES ('Lodge');
INSERT INTO "Traits" VALUES ('London');
INSERT INTO "Traits" VALUES ('Madness');
INSERT INTO "Traits" VALUES ('Mainland');
INSERT INTO "Traits" VALUES ('Manifold');
INSERT INTO "Traits" VALUES ('Marrakesh');
INSERT INTO "Traits" VALUES ('Mask');
INSERT INTO "Traits" VALUES ('Medic');
INSERT INTO "Traits" VALUES ('Melee');
INSERT INTO "Traits" VALUES ('Mexico City');
INSERT INTO "Traits" VALUES ('Mi-Go');
INSERT INTO "Traits" VALUES ('Midtown');
INSERT INTO "Traits" VALUES ('Mirage');
INSERT INTO "Traits" VALUES ('Miskatonic');
INSERT INTO "Traits" VALUES ('Mnar');
INSERT INTO "Traits" VALUES ('Monster');
INSERT INTO "Traits" VALUES ('MontrÃ©al');
INSERT INTO "Traits" VALUES ('Mountain');
INSERT INTO "Traits" VALUES ('Mountains');
INSERT INTO "Traits" VALUES ('Mutated');
INSERT INTO "Traits" VALUES ('Mystery');
INSERT INTO "Traits" VALUES ('New Orleans');
INSERT INTO "Traits" VALUES ('New York City');
INSERT INTO "Traits" VALUES ('Nightgaunt');
INSERT INTO "Traits" VALUES ('Obstacle');
INSERT INTO "Traits" VALUES ('Occult');
INSERT INTO "Traits" VALUES ('Ocean');
INSERT INTO "Traits" VALUES ('Omen');
INSERT INTO "Traits" VALUES ('Ooth-Nargai');
INSERT INTO "Traits" VALUES ('Ooze');
INSERT INTO "Traits" VALUES ('Oozified');
INSERT INTO "Traits" VALUES ('Oriab');
INSERT INTO "Traits" VALUES ('Otherworld');
INSERT INTO "Traits" VALUES ('Outsider');
INSERT INTO "Traits" VALUES ('Pact');
INSERT INTO "Traits" VALUES ('Paradox');
INSERT INTO "Traits" VALUES ('Paris');
INSERT INTO "Traits" VALUES ('Part 1');
INSERT INTO "Traits" VALUES ('Passageway');
INSERT INTO "Traits" VALUES ('Past');
INSERT INTO "Traits" VALUES ('Patron');
INSERT INTO "Traits" VALUES ('Performer');
INSERT INTO "Traits" VALUES ('Pnakotus');
INSERT INTO "Traits" VALUES ('Poison');
INSERT INTO "Traits" VALUES ('Police');
INSERT INTO "Traits" VALUES ('Port');
INSERT INTO "Traits" VALUES ('Portal');
INSERT INTO "Traits" VALUES ('Possessed');
INSERT INTO "Traits" VALUES ('Power');
INSERT INTO "Traits" VALUES ('Practiced');
INSERT INTO "Traits" VALUES ('Present');
INSERT INTO "Traits" VALUES ('Present-Day');
INSERT INTO "Traits" VALUES ('Prison');
INSERT INTO "Traits" VALUES ('Private');
INSERT INTO "Traits" VALUES ('Providence');
INSERT INTO "Traits" VALUES ('Rail');
INSERT INTO "Traits" VALUES ('Ranged');
INSERT INTO "Traits" VALUES ('Relic');
INSERT INTO "Traits" VALUES ('Reporter');
INSERT INTO "Traits" VALUES ('Research');
INSERT INTO "Traits" VALUES ('Resident');
INSERT INTO "Traits" VALUES ('Resolute');
INSERT INTO "Traits" VALUES ('Return');
INSERT INTO "Traits" VALUES ('Risen');
INSERT INTO "Traits" VALUES ('Ritual');
INSERT INTO "Traits" VALUES ('Ritual Site');
INSERT INTO "Traits" VALUES ('River');
INSERT INTO "Traits" VALUES ('Riverside');
INSERT INTO "Traits" VALUES ('Road');
INSERT INTO "Traits" VALUES ('Rot');
INSERT INTO "Traits" VALUES ('Ruins');
INSERT INTO "Traits" VALUES ('Salem');
INSERT INTO "Traits" VALUES ('Sanctum');
INSERT INTO "Traits" VALUES ('Scheme');
INSERT INTO "Traits" VALUES ('Scholar');
INSERT INTO "Traits" VALUES ('Science');
INSERT INTO "Traits" VALUES ('Scientist');
INSERT INTO "Traits" VALUES ('Script');
INSERT INTO "Traits" VALUES ('Second Floor');
INSERT INTO "Traits" VALUES ('Sentinel Hill');
INSERT INTO "Traits" VALUES ('Serpent');
INSERT INTO "Traits" VALUES ('Service');
INSERT INTO "Traits" VALUES ('Servitor');
INSERT INTO "Traits" VALUES ('Shantak');
INSERT INTO "Traits" VALUES ('Shattered');
INSERT INTO "Traits" VALUES ('Ship');
INSERT INTO "Traits" VALUES ('Shoggoth');
INSERT INTO "Traits" VALUES ('Silver Twilight');
INSERT INTO "Traits" VALUES ('Skai');
INSERT INTO "Traits" VALUES ('Socialite');
INSERT INTO "Traits" VALUES ('Song');
INSERT INTO "Traits" VALUES ('Sorcerer');
INSERT INTO "Traits" VALUES ('Spectral');
INSERT INTO "Traits" VALUES ('Spell');
INSERT INTO "Traits" VALUES ('Spider');
INSERT INTO "Traits" VALUES ('Spirit');
INSERT INTO "Traits" VALUES ('St Mary''s');
INSERT INTO "Traits" VALUES ('Stable');
INSERT INTO "Traits" VALUES ('Staff');
INSERT INTO "Traits" VALUES ('Steps');
INSERT INTO "Traits" VALUES ('Summon');
INSERT INTO "Traits" VALUES ('Supply');
INSERT INTO "Traits" VALUES ('Surface');
INSERT INTO "Traits" VALUES ('Suspect');
INSERT INTO "Traits" VALUES ('Syndicate');
INSERT INTO "Traits" VALUES ('Synergy');
INSERT INTO "Traits" VALUES ('Tactic');
INSERT INTO "Traits" VALUES ('Talent');
INSERT INTO "Traits" VALUES ('Tarot');
INSERT INTO "Traits" VALUES ('Task');
INSERT INTO "Traits" VALUES ('Temple');
INSERT INTO "Traits" VALUES ('TenochtitlÃ¡n');
INSERT INTO "Traits" VALUES ('Tentacle');
INSERT INTO "Traits" VALUES ('Terror');
INSERT INTO "Traits" VALUES ('Third Floor');
INSERT INTO "Traits" VALUES ('Tindalos');
INSERT INTO "Traits" VALUES ('Tome');
INSERT INTO "Traits" VALUES ('Tool');
INSERT INTO "Traits" VALUES ('Tower');
INSERT INTO "Traits" VALUES ('Town');
INSERT INTO "Traits" VALUES ('Train');
INSERT INTO "Traits" VALUES ('Trap');
INSERT INTO "Traits" VALUES ('Trick');
INSERT INTO "Traits" VALUES ('Unbroken');
INSERT INTO "Traits" VALUES ('Uncharted');
INSERT INTO "Traits" VALUES ('Unhallowed');
INSERT INTO "Traits" VALUES ('Unstable');
INSERT INTO "Traits" VALUES ('Upgrade');
INSERT INTO "Traits" VALUES ('Vale');
INSERT INTO "Traits" VALUES ('Vehicle');
INSERT INTO "Traits" VALUES ('Venice');
INSERT INTO "Traits" VALUES ('Veteran');
INSERT INTO "Traits" VALUES ('Void');
INSERT INTO "Traits" VALUES ('Warden');
INSERT INTO "Traits" VALUES ('Wastes');
INSERT INTO "Traits" VALUES ('Wayfarer');
INSERT INTO "Traits" VALUES ('Weapon');
INSERT INTO "Traits" VALUES ('Wilderness');
INSERT INTO "Traits" VALUES ('Witch');
INSERT INTO "Traits" VALUES ('Witch House');
INSERT INTO "Traits" VALUES ('Woods');
INSERT INTO "Traits" VALUES ('Y''ha-nthlei');
INSERT INTO "Traits" VALUES ('Yithian');
INSERT INTO "Traits" VALUES ('Yoth');
INSERT INTO "Traits" VALUES ('Yuggoth');
INSERT INTO "Traits" VALUES ('Zoog');
INSERT INTO "Types" VALUES ('Asset');
INSERT INTO "Types" VALUES ('Event');
INSERT INTO "Types" VALUES ('Skill');
COMMIT;
